name: Build GoDroid Automator APK

on:
  push:
    branches:
      - godroid-automator-app

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.1.1'

      - name: Inject Version Name
        run: |
          sed -i -E 's/versionName = "[0-9.]+"/versionName = "3.${{ github.run_number }}"/g' app/build.gradle.kts
          sed -i -E 's/versionCode = [0-9]+/versionCode = ${{ github.run_number }}/g' app/build.gradle.kts

      - name: Build APK (Android)
        run: gradle assembleDebug

      - name: Renommer l'APK pour la Release
        run: cp app/build/outputs/apk/debug/app-debug.apk GoDroid-Automator-v3.${{ github.run_number }}.apk

      - name: Ajouter l'APK a la Release (Lien Direct)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v3.${{ github.run_number }}
          files: GoDroid-Automator-v3.${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK pour le téléchargement
        uses: actions/upload-artifact@v4
        with:
          name: GoDroid-Automator-APK
          path: app/build/outputs/apk/debug/app-debug.apk
